# Generated by Django 4.2.7 on 2023-12-05 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_opinion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 12, 31, 22, 897275, tzinfo=datetime.timezone.utc)),
        ),
    ]
