# Generated by Django 4.2.7 on 2023-12-06 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_opinion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
