# Generated by Django 4.2.7 on 2023-12-06 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_opinion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 16, 39, 22, 119247, tzinfo=datetime.timezone.utc)),
        ),
    ]
