# Generated by Django 4.2.7 on 2023-12-06 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 6, 21, 33, 7, 596725, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
