# Generated by Django 4.2.7 on 2023-12-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_first_name_order_last_name'),
        ('order', '0003_alter_order_shipping_status'),
    ]

    operations = [
    ]
