# Generated by Django 4.2.7 on 2023-12-02 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_arduuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arduuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='arduuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='arduuser',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='arduuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
